### ISSUE TITLE
down direction requires stone type, but other directions don't

### ISSUE THREAD

**Issue by nightpool** [gruppler/PTN-Ninja#12]
![image](https://cloud.githubusercontent.com/assets/233815/18354507/d3dd51fa-75b3-11e6-892d-5da2910b5de2.png)
vs 
![image](https://cloud.githubusercontent.com/assets/233815/18354510/d782a918-75b3-11e6-9114-cf826d3eb1af.png)

this works:

![image](https://cloud.githubusercontent.com/assets/233815/18354548/fe8b348a-75b3-11e6-9732-0be6b9a8428b.png)

this is on Chrome 52 on Mac, on ptn.ninja

**Comment by gruppler** [comment]
Already fixed in development branch.

**Comment by nightpool** [comment]
thanks!

**Comment by gruppler** [comment]
Well, the layout in development is currently broken but I'll be rewriting it very soon.
