### ISSUE TITLE
TimeControl tag breaks the site

### ISSUE THREAD

**Issue by chaitu236** [gruppler/PTN-Ninja#14]
playtak.com's games now have a TimeControl tag to indicate timer information. This breaks the site. You can maybe ignore unknown tags?

**Comment by Brotherbag** [comment]
Related is that Playtak scores a draw as "1-2-1-2" which is not compatible with ptn.nija.

**Comment by gruppler** [comment]
Well, "1-2-1-2" is just wrong. According to the spec, it should be "1/2-1/2" so feel free to open an issue on PlayTak's github page to fix that.

I will make ptn.ninja accept the wrong notation as well, though.

**Comment by gruppler** [comment]
Also, TimeControl isn't in the spec, and I have no idea what it does.

**Comment by chaitu236** [comment]
TimerControl is updated to Clock and conforms with spec now. Fixed draw to "1/2-1/2"

**Comment by gruppler** [comment]
Ok, cool!

**Comment by chaitu236** [comment]
Clock tag still broken

**Comment by gruppler** [comment]
How so?

**Comment by chaitu236** [comment]
I get an "Invalid Clock: .. " error for any game with Clock tag. e.g., https://www.playtak.com/games/90680/ninjaviewer

**Comment by gruppler** [comment]
Ok, yeah. It's already been fixed in the development branch.

**Comment by chaitu236** [comment]
ah ok.. didn't realiz

**Comment by gruppler** [comment]
No prob. Almost every issue so far has already been fixed. I keep thinking I'm going to be pushing everything live soon, but each feature leads to the next, and I'm too lazy to cherrypick to master.

**Comment by chaitu236** [comment]
Understandable..

**Comment by gruppler** [comment]
Fixed in a71a3ed
