### ISSUE TITLE
Unplayed piece count

### ISSUE THREAD

**Issue by Brotherbag** [gruppler/PTN-Ninja#15]
It would be nice when in play mode to be able to see the current count of each player's remaining pieces, as this is often relevant to the game, making it clear if one player can start forcing a flat win or not.

Counting the pieces on the board is annoying and most people (especially me) are bad at doing it.

**Comment by gruppler** [comment]
Already done in the development branch.

**Comment by Brotherbag** [comment]
Ideal, thanks.
