### ISSUE TITLE
Add flat count and/or remaining stones

### ISSUE THREAD

**Issue by robertos** [gruppler/PTN-Ninja#2]
Useful for when using ptn.ninja links for async play (e.g. play-by-email, play-by-IM). 
It would be great to show the remaining piece count and/or the flat score to evaluate a possible flat victory without having to count stones

**Comment by gruppler** [comment]
Believe it or not, that's the very next thing on my list.  Check out the development branch for a preview.

**Comment by robertos** [comment]
Awesome! :+1:  Let me know if I can help! :)
