### ISSUE TITLE
Pieces invisible in Firefox Quantum browser

### ISSUE THREAD

**Issue by cdbfoster** [gruppler/PTN-Ninja#28]
Under both Linux and Windows 10.  Everything works fine under Chrome on the same computer, and it all worked fine on previous versions of Firefox.  I'm sure this is related to the recent release of Firefox Quantum.

**Comment by gruppler** [comment]
Thanks for the report, but this is already fixed in the latest (unreleased) version. You can try it out at http://dev.ptn.ninja.
