### ISSUE TITLE
Off by one comments

### ISSUE THREAD

**Issue by nqeron** [gruppler/PTN-Ninja#29]
It seems to me that the way the comments display is off by one - that is, they appear before the annotated move is placed on the board.  For example
![download](https://user-images.githubusercontent.com/1817331/36884298-12b59f56-1dae-11e8-9eeb-8fbd7460c9e2.png) shows the annotation for the upcoming move rather than the one just played (f6 {adjacent corners}).

Can this be tweaked?

**Comment by gruppler** [comment]
This weirdness comes from my attempt to make consistent the relationships between the annotations, the board state, and the current ply, while also allowing easy back/forward navigation. Moving forward performs the selected ply and then selects the next one. This affords some foreknowledge to direct the user's eyes before the ply is actually performed.

Here is my reasoning for treating them differently: Tak and Tinuë correspond to the board state rather than the selected ply, but comments correspond to the selected ply. I'm open to persuasion regarding this point, though.

The simplest workaround that comes to mind is to swap the "half-ply" navigation with the current (so holding Shift while pressing left/right would navigate by whole steps instead).

**Comment by rabbitboy84** [comment]
Most comments that I do (I can't speak for others) involve the current board state, so it was confusing to write the comments beside the next turn. I worked around it, but it definitely involved a bit of mental juggling.

Also, using your branching, it would make sense to tie the annotations to the currently played ply. Then, it would look something like this:

Current board state with 3 or 4 highlighted branch options for next ply. "Black has made a simple Tak threat. White could use any of these options to counter. Use the numbers to follow the result of each."

Just my thoughts. Keep up the good work; I love your program!

**Comment by gruppler** [comment]
It seems like the counter-intuitive behavior stems from selecting the next ply after performing the current one, or in other words, leaving the ply undone when navigating to it. Does this sound accurate?

**Comment by rabbitboy84** [comment]
I like the highlighting of the squares, just would like the annotations to
be tied to the current board state and not the highlighted squares.

**Comment by gruppler** [comment]
I see. My concern with that is that after the ply is done, it's not obvious what the comment is referring to (except immediately after watching the ply happen). Instead, what's left are the highlighted squares of a _different_ ply, which seems like it could be easily misinterpreted as corresponding to the currently displayed comment.

**Comment by rabbitboy84** [comment]
I see. Yes, that could be confusing for someone not familiar with the
software.

But, if you removed the highlighting, how would you handle the branching? I
think the highlighting really aids in those instances.

**Comment by gruppler** [comment]
I agree, I'm not suggesting getting rid of the highlighting. I think it just needs to correspond to the most useful and intuitive things in every situation.

**Comment by gruppler** [comment]
I made some changes to navigation. Kinda difficult to explain, probably easier to just try it and see if it resolves the issues.

**Comment by rabbitboy84** [comment]
Thanks! I'll have to find some time to explore it.

**Comment by nqeron** [comment]
Been a while since I've last used PTN ninja, so it's kind of hard for me to pick out the differences.  I'm not sure if this is new, but I'm getting highlights for alternative branches (which I'm debating whether I like or not) but not for the next move (which is the behavior I prefer).

Maybe if highlighting for next move is on, the comments should line up with the highlighted move, but if it's off it should line up with the current board state? Just an idea.
