### ISSUE TITLE
Show notation side-by-side with "play" mode

### ISSUE THREAD

**Issue by nelhage** [gruppler/PTN-Ninja#3]
I find myself really missing (from the ptnviewer fiddle) the ability to step through the game in read-only mode with the notation side-by-side with the board. It's useful to be able to see move numbers and notation when commenting on a game or reading a game that is commented elsewhere.

**Comment by gruppler** [comment]
Originally, I planned to have an option to see the PTN in play mode, but I
realized that wouldn't be much different from edit mode with play controls.

I'm planning to add a slide-out menu to house preferences and things, so
maybe that will be a good place for that option. Unless you have something
more clever in mind?

**Comment by nelhage** [comment]
The big difference in my mind is that arrow keys and space move ply-by-ply in view mode, vs. interacting with the text in edit mode.

A preference in a slide-out menu (stored in `localStorage` or whatever) makes sense to me.

**Comment by gruppler** [comment]
Yeah, hotkeys would be the main reason I'd want it too.

Yep, I'll store preferences in localStorage, and there will also be an embed code generator that will allow including preferences and other things in the URL.

**Comment by gruppler** [comment]
Any ideas for showing the PTN and board in play mode on small screens? In edit mode, they overlap but the PTN takes priority and heavily obstructs the board. Maybe it should be a desktop-only feature (since they generally are the ones with physical keyboards)? Or just limit it to a wide aspect ratio?

**Comment by nelhage** [comment]
Yeah, I think desktop-only makes sense. I'd love to see the current move (and maybe notation for both plies in the current PTN move) below the board on mobile, I think.

**Comment by gruppler** [comment]
Ok, I have an idea. This will be sweet.

**Comment by Daenyth** [comment]
How about on small screens, only showing a snippet of the notation? Maybe the current move line only, or current/prev/next move line with the current highlighted?

On the larger screens I think the current move should be highlighted in some way as well, in the notation.

**Comment by gruppler** [comment]
I ended up just showing the plies for the current move between the player name and flat count, which are listed horizontally above the board.

**Comment by gruppler** [comment]
@nelhage, when you get a chance, could you please try out the development branch and let me know if this kind of ply display suits you?

**Comment by nelhage** [comment]
Personally, I'd rather something that has the normal notation -- `1. a5 e1` -- including the move number, since I'd find it easier to parse at a glance (I find the current top bar pretty busy), and because the move number is useful context when discussing a game (I'll refer to `35. b2` or `35.W` if I'm writing discussion or something). 

But I'm definitely happier with it there as-is than not!

**Comment by gruppler** [comment]
My original idea (that I said would be sweet) was to put the whole line as
it appears below the board, and when it changes, there'd be a vertical
transition. The image that came to mind was sort of like a slot machine
display. But then I thought adding to the bottom would be wasteful of
space, and I'd be changing the aspect ratio of the board display, which
would require fiddling with the CSS for the board's responsiveness.

What do you think about the new navigation behavior?

**Comment by nelhage** [comment]
What did you change around navigation?

**Comment by gruppler** [comment]
It's kind of hard to explain. Basically, when you undo a move, the active
move doesn't change (until you "undo" again). So the active move may or may
not be "done."

**Comment by nelhage** [comment]
Oh, I did notice that when arrowing through, and thought it was a bug. It's
an interesting idea and makes some sense, but without better UI hinting it
just threw me.

**Comment by gruppler** [comment]
Better UI hinting? Please explain.

**Comment by nelhage** [comment]
I just mean somehow making the distinction about the "current position" the
UI is sitting at being clearer somehow -- the distinction between the
displayed moves being about to happen vs. having just happened.

**Comment by gruppler** [comment]
Haha oops. Just overwrote your reply. Didn't know that was possible.

**Comment by nelhage** [comment]
[edited back] outlined/filled ply text might help, yeah.
