### ISSUE TITLE
Alternate lines corrupted in editor mode

### ISSUE THREAD

**Issue by nqeron** [gruppler/PTN-Ninja#32]
I have found a bug where the editor is corrupted due to weird alternate line stuff.  I have two pictures.  To reproduce: Play a few moves in a PTN game (or find an old game). Find a position where white or black captures a piece the turn after which it is placed. (e.g. 4. d4 e4<). Then use the navigation arrows to wind back to the placement and replace it with a noble (I know this works with a wall and am assuming it will with a capstone). Then play one more move with the color that would have done the capture. (unknown atm if this will reproduce will more moves, but fairly likely) Then go to the editor and note that the alternative lines are off and incorrect. If you edit anything - even the name of a player it should start complaining about illegal moves.  

Ideally, I'd like to produce a short duplication video, but I don't have the time atm, so I'm hoping this will be sufficient.

![ptnninja2](https://user-images.githubusercontent.com/1817331/46253512-7dfb1b80-c44b-11e8-9761-f31bd9f83e68.png)
![ptnninja1](https://user-images.githubusercontent.com/1817331/46253513-7e93b200-c44b-11e8-9b44-b6dcf1ac9060.png)

**Comment by gruppler** [comment]
Good catch, I'll have to take some time to look into this and think about how to resolve it. Thanks!
