### ISSUE TITLE
Link from playtak.com not loading on mobile

### ISSUE THREAD

**Issue by nqeron** [gruppler/PTN-Ninja#34]
I'm not sure if this is a PTN ninja issue or a playtak issue or both, but when I click the ptn.ninja link on a given game from the history page of playtak on my iPhone it brings me to a blank game, rather than loading in the game on file.

**Comment by gruppler** [comment]
I tried unsuccessfully to reproduce this problem on my Windows desktop and my Android phone. I'm thinking it's a PlayTak issue, or an iPhone issue, but I'll leave this open in case more information becomes available.

**Comment by nqeron** [comment]
I tried this out with the Chrome browser on my phone and got it to work.  Maybe it's an issue with Safari?  I'll have to try out Safari on a Mac when I get a chance.
