### ISSUE TITLE
Embeds not displaying in Chrome on iOS

### ISSUE THREAD

**Issue by nqeron** [gruppler/PTN-Ninja#39]
The embedded <iFrame> that I'm using for my blog appear blank when using Chrome on iOS.

**Comment by gruppler** [comment]
I just opened your blog on both Chrome and Safari on an iPad, and both worked after some waiting. My guess is that your device doesn't have enough memory to load the iFrame, especially if you're loading the home page with multiple posts, or maybe you're not waiting long enough.

Unfortunately, I don't have iOS devices of my own to test on, so I have to rely on borrowed devices when I can get my hands on them.
