### ISSUE TITLE
PTN ninja link from play tak history broken?

### ISSUE THREAD

**Issue by nqeron** [gruppler/PTN-Ninja#41]
I tried navigating to a game from the play tak history viewer using the PTN ninja link, and it wasn't working. (Chrome - Mac OS X)

**Comment by gruppler** [comment]
Which link was it?

**Comment by nqeron** [comment]
Seems to be working just fine from Mobile. Maybe it was a browser cache error? I'll try to replicate the issue later.

**Comment by gruppler** [comment]
Until the PlayTak links get fixed, you can work around the problems by either downloading the game file or viewing it and copying/pasting into ptn.ninja.
