### ISSUE TITLE
Listed moves in alternate paths doesn't always work

### ISSUE THREAD

**Issue by nqeron** [gruppler/PTN-Ninja#44]
**Describe the bug**

The ply for the top of an alternate branch is showing instead of the appropriate one.

**To Reproduce**

Create a game with multiple branches and steps of those branches.
Manually rewind to the fork
Manually take a previously explored alternate.
In the top, where the plies are, the previous branches' ply is listed instead of the correct one.

![backtrack_01](https://user-images.githubusercontent.com/1817331/81747205-ae06ff00-9475-11ea-8745-30d19c3e8285.png)
![backtrack_02](https://user-images.githubusercontent.com/1817331/81747208-ae9f9580-9475-11ea-8d77-447923c6580c.png)

**Comment by gruppler** [comment]
What exactly do you mean by "Manually take a previously explored alternate"?

**Comment by nqeron** [comment]
Play the moves out on the board. Rather than navigating through branches.

**Comment by gruppler** [comment]
I think I've noticed this a few times in the past but am not currently able to reproduce it. There must be more factors involved in its manifestation. Are you able to reliably reproduce it?
