### ISSUE TITLE
Timeline navigation error

### ISSUE THREAD

**Issue by nqeron** [gruppler/PTN-Ninja#49]
[PTN Ninja](https://ptn.ninja/NoZQlgLgpgBARABQDYEMCeAVFBrAdAYwHsBbOAXQFgAoYAUQDcoA7CeAeSaTCdmXXOrA+aKACcAjPADqAC0hQBNYWIBM8AEKp82RcADCSQtvjiADAC5TMANTiArLoBKUAM4BXJKziOAtKd3gAF6wcABsuhgIIPAAHioANAni8ckxAPSpKeJJ4rkqICkqKsniaXGJWTnFKnrx6TEpBclF4rVxZUnFBcUpKWkJA3VJMJIAzADsugAiKNDwKqYLuNm4ixFgxCHioZZ25gAsAByK1BO4MKMAJqPWxQBUMCDXp4fndpd2ADy5ozC+ptRqABvCYAIx84gAvlQzjAfD4YHYoPtrKMVC83h8IXk-n4gA&name=CIQwlgNgngBACgVwF5IgUxgYgOwE4B0ATDABQCiA5BGAE4CUQA&targetBranch=MwdgRgtAjEA&ply=0)

In navigating this game, I can navigate to the end, but then have an issue navigating back to the beginning of the timeline.

**Comment by gruppler** [comment]
What issue do you have? How are you navigating? I'm not seeing any problems.

**Comment by nqeron** [comment]
I think it got the wrong link: this is the link that I got from rabbitboy: [PTN Ninja](https://ptn.ninja/NoZQlgLgpgBARABQDYEMCeAVFBrAdAYwHsBbOAXQFgAoYAUQDcoA7CeAeSaTCdmXXOrAAIimjwATAAYpuAIzjckgCwCaGMMVhxJkgFziAbLoCsB1cD5ooAJ1nx1SCDgD6AIUIRzlm+PgBxAFcoAGcIKUNzAGEkQnxseFljXUkYAGpZSXMAJRCAx3gsgFpMyhpwAC8tY3MMBBB4AA8AGnEm2TaQFoB6Zvb28U7xcVl5UZAuvrbItpbx4dbW5tbZLoW++WnhwZg7cWrS6kNcGChxAB4YFGNDgHZj05giySA&name=CoSwNgLghg1g%2BgIQPYQAQDcDOqDiBXAU0wgCYAGEgNlQFYAPG1AJQFozVzyA6ARhK7IAWNmS5UuNSkA&ply=4)

**Comment by gruppler** [comment]
Looks like the problem was caused by a mismatch between the first move number as specified in the TPS and the first move according to the PTN.

Do you know whether this game was altered using TPS edit mode? It automatically sets the move to a reasonable guess, but I'm wondering if that's an undesirable feature.

**Comment by gruppler** [comment]
I'm also not sure what I should do to handle this edge case. Report it as an error? Just use the PTN move number and correct the TPS?
