### ISSUE TITLE
In the embed preview white's flat-count has too little padding right when in the double digits

### ISSUE THREAD

**Issue by nitzel** [gruppler/PTN-Ninja#63]
**Describe the bug**
The embed preview is 
1. ~~missing the player names.~~
2. not padding white's flat-count enough when it has 2 digits

**To Reproduce**
1. Create a new game
2. Drop enough flats so that white has a 2-digit flat-count or just [click here](https://ptn.ninja/NoZQlgXgpgBARAVjgXQLAChgAUA2BDATygCcBGeAeQDsoUNt8jiAmeAFQHcB7OzcAF1hwADvyoA6KmCoArPL2AARPIPjMADM1Lj125gE4FbMAFsh6gBwAuBMysbeGbTDwIYAIwQZm4mAGM3ABMvdABmXyg3KAAWDGjfQOj-WPQEX3ckvBSANl88UI9QjAB2Xz8CwKL0CwiCqGYMfQTWPwb0UnV01jxmIA&name=PIAgbgziIKwB4yA&ply=19!)
3. Click on share->embed

**Expected behavior**
1. White's flat count should have the same padding-right as black's has padding-left

**Screenshots**
![image](https://user-images.githubusercontent.com/8362046/106253598-9ba14100-620f-11eb-867d-d5a9a7556fa4.png)

**Desktop:**
 - OS: `Microsoft Windows 10 Pro 10.0.19042 N/A Build 19042`
 - Browser: Chrome
 - Version 88.0.4324.104 (Official Build) (64-bit)

**Comment by gruppler** [comment]
Are you sure you don't just have the Player Names option turned off?

**Comment by nitzel** [comment]
Embarrassingly I wasn't even aware of that setting. My bad. Then it's only about the padding.
