### ISSUE TITLE
moves and notes sidebars at the same time

### ISSUE THREAD

**Issue by Skoolin** [gruppler/PTN-Ninja#65]
I think both the moves pane on the left and the notes pane on the right are strong tools. Right now I don't use the notes because then I cannot see the moves anymore. Instead I write down notes somewhere else. If they where both visible at the same time, I think that would be great!

**Comment by gruppler** [comment]
If the window is wide enough, it will show both. What kind of device are you using, and what are the screen dimensions?

**Comment by Skoolin** [comment]
It is a notebook with 1366x768

**Comment by gruppler** [comment]
I'll lower the threshold for showing both panels simultaneously to 1366. Any lower and the board will probably shrink too much.
